# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calendar < Formula
  desc "swiss knife for services"
  homepage "https://github.com/worldline-go/calendar"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/worldline-go/calendar/releases/download/v0.1.2/calendar_Darwin_x86_64.tar.gz"
      sha256 "2f65e3982fda13491d6c081f7ae64736d138a6fdcb28f138d810349efec15e91"

      def install
        bin.install "calendar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/worldline-go/calendar/releases/download/v0.1.2/calendar_Darwin_arm64.tar.gz"
      sha256 "81a843c0c771ac70df4ee0e8976e9815a4911da1f1e7c68c25452eb320967031"

      def install
        bin.install "calendar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/worldline-go/calendar/releases/download/v0.1.2/calendar_Linux_x86_64.tar.gz"
        sha256 "064822d357cff8364f3ca0542271c77a694fd3fefe2469dafd03b6c72f1097f5"

        def install
          bin.install "calendar"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/worldline-go/calendar/releases/download/v0.1.2/calendar_Linux_armv6.tar.gz"
        sha256 "69a045b0c2c9132706407f4af753537b01788959820d6188fafe3d73a6495747"

        def install
          bin.install "calendar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/worldline-go/calendar/releases/download/v0.1.2/calendar_Linux_arm64.tar.gz"
        sha256 "98b62701f3fcecb2a0b1ef774b8692d631a777c465b07d52ccf3c3262e0d97c5"

        def install
          bin.install "calendar"
        end
      end
    end
  end
end
