# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calendar < Formula
  desc "swiss knife for services"
  homepage "https://github.com/worldline-go/calendar"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/worldline-go/calendar/releases/download/v0.1.0/calendar_Darwin_x86_64.tar.gz"
      sha256 "0f5e89fdaf273fcb467cd6b27b98e53d9cc90e64929f7a816256a098a5f40016"

      def install
        bin.install "calendar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/worldline-go/calendar/releases/download/v0.1.0/calendar_Darwin_arm64.tar.gz"
      sha256 "50928adc79e8660b5ccd5a2a744318c51a85033716db95aa169f1209fac2895a"

      def install
        bin.install "calendar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/worldline-go/calendar/releases/download/v0.1.0/calendar_Linux_x86_64.tar.gz"
        sha256 "84580622147f7dc9a69235c0a98ac050c319294f8cd0a80d72aa3792aa3f3a8c"

        def install
          bin.install "calendar"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/worldline-go/calendar/releases/download/v0.1.0/calendar_Linux_armv6.tar.gz"
        sha256 "b720429aa08cd968e095913ea7df5f3fd0325c67af070d25f29bb6358b5ac005"

        def install
          bin.install "calendar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/worldline-go/calendar/releases/download/v0.1.0/calendar_Linux_arm64.tar.gz"
        sha256 "528fc287941868d205b0aadb76ac1003891ec798f140333cf118190ec13befc7"

        def install
          bin.install "calendar"
        end
      end
    end
  end
end
