# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fine < Formula
  desc "file management service"
  homepage "https://github.com/rytsh/fine"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rytsh/fine/releases/download/v0.1.1/fine_Darwin_x86_64.tar.gz"
      sha256 "68503d913fc268747a80eda69700b4231a083d7c5051fcd6ee109be6e1bce74b"

      def install
        bin.install "fine"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rytsh/fine/releases/download/v0.1.1/fine_Darwin_arm64.tar.gz"
      sha256 "8f2906662541f5c9aa1b89753fdd6f6364deab42844788b222412920adb391c7"

      def install
        bin.install "fine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rytsh/fine/releases/download/v0.1.1/fine_Linux_arm.tar.gz"
      sha256 "19929b1413e2528504efea72df6836a97dbf0fbed3ca6efd56317cfbbbe5922f"

      def install
        bin.install "fine"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rytsh/fine/releases/download/v0.1.1/fine_Linux_x86_64.tar.gz"
      sha256 "5ee146ca3a10e1ea756db82fe52258e907bfc3a5af1c37b23304a66cad33ca6e"

      def install
        bin.install "fine"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rytsh/fine/releases/download/v0.1.1/fine_Linux_arm64.tar.gz"
      sha256 "f650e61bf4039393660fe2dccf1b4328071124d4d2db9770c9cec4aa9ab1cd35"

      def install
        bin.install "fine"
      end
    end
  end
end
