# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fine < Formula
  desc "file management service"
  homepage "https://github.com/rytsh/fine"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rytsh/fine/releases/download/v0.1.0/fine_Darwin_x86_64.tar.gz"
      sha256 "2069dfa66cbd5d2f79b8ba355eedafd167aa9238de4440e3763e545b76cd660f"

      def install
        bin.install "fine"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rytsh/fine/releases/download/v0.1.0/fine_Darwin_arm64.tar.gz"
      sha256 "e2045b6320f7111d54d475ec5c4bbb8843ce40c5ca1dfaaa15c0a6c157aa7ca7"

      def install
        bin.install "fine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rytsh/fine/releases/download/v0.1.0/fine_Linux_arm.tar.gz"
      sha256 "d12ca4be922631ab41f128731c27d7758d0348eb592ae0359cfadf2fc2e57744"

      def install
        bin.install "fine"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rytsh/fine/releases/download/v0.1.0/fine_Linux_x86_64.tar.gz"
      sha256 "0578ca45f275098ebc0698b3e066f5e84370299482262b3c75df6b69b06359e2"

      def install
        bin.install "fine"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rytsh/fine/releases/download/v0.1.0/fine_Linux_arm64.tar.gz"
      sha256 "aeeae2a2fae468a14036cca6c8bd49c3749b4a15b25d5ab2b17f30ba9379b982"

      def install
        bin.install "fine"
      end
    end
  end
end
