# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forward < Formula
  desc "export socket connections"
  homepage "https://github.com/worldline-go/forward"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/worldline-go/forward/releases/download/v0.2.0/forward_Darwin_x86_64.tar.gz"
      sha256 "4c3cc27b36fcea4b3ef694f50ed7a4e2fbc87090752b6b756cd221461ba9a216"

      def install
        bin.install "forward"
      end
    end
    on_arm do
      url "https://github.com/worldline-go/forward/releases/download/v0.2.0/forward_Darwin_arm64.tar.gz"
      sha256 "d965ebc1ecc81f3021c026ea9b1a37320226eaa1d9b703b43e8e9caad7d8ab0d"

      def install
        bin.install "forward"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/worldline-go/forward/releases/download/v0.2.0/forward_Linux_x86_64.tar.gz"
        sha256 "3a7f4b76276e7cd43f87d12eb6dcc243a4f2470530409377f672fd329fb0fb4f"

        def install
          bin.install "forward"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/worldline-go/forward/releases/download/v0.2.0/forward_Linux_arm64.tar.gz"
        sha256 "3a296d30b16637fff2558ed2d3165916d4eb7acb800d11b70f68ce5a148bf46e"

        def install
          bin.install "forward"
        end
      end
    end
  end
end
