# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotouch < Formula
  desc "customizable project creator"
  homepage "https://denizgursoy.github.io/gotouch/"
  version "1.7.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/denizgursoy/gotouch/releases/download/v1.7.3/gotouch_1.7.3_Darwin_x86_64.tar.gz"
      sha256 "65232b5f303547306f537e008e94c2ce2118a33f590d7d2dd575fcdd77fd88c7"

      def install
        bin.install "gotouch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/denizgursoy/gotouch/releases/download/v1.7.3/gotouch_1.7.3_Darwin_arm64.tar.gz"
      sha256 "3c0f7073871f6283ef1831469e53130828f6e6c55de5a0e2dd8068f6f75bc3f3"

      def install
        bin.install "gotouch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/denizgursoy/gotouch/releases/download/v1.7.3/gotouch_1.7.3_Linux_arm64.tar.gz"
      sha256 "db1bb25a30c5c7bab1befbd7cc6764a781a7d3640ac69fd75d0402edeb8add00"

      def install
        bin.install "gotouch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/denizgursoy/gotouch/releases/download/v1.7.3/gotouch_1.7.3_Linux_x86_64.tar.gz"
      sha256 "18d01cb62adc7e59a72f8ae986f6330b65adf98063becd9e45a8bbc1b7220bbc"

      def install
        bin.install "gotouch"
      end
    end
  end
end
