# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotouch < Formula
  desc "customizable project creator"
  homepage "https://denizgursoy.github.io/gotouch/"
  version "1.11.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/denizgursoy/gotouch/releases/download/v1.11.0/gotouch_1.11.0_Darwin_arm64.tar.gz"
      sha256 "57b89d5aeb4e90a50abae4045f0f7f71bef92585e10d7c68b8a2622ab3e9e26b"

      def install
        bin.install "gotouch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/denizgursoy/gotouch/releases/download/v1.11.0/gotouch_1.11.0_Darwin_x86_64.tar.gz"
      sha256 "0288199749396542d77a74281da09c88c4145be038d0722094394cd21678ec98"

      def install
        bin.install "gotouch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/denizgursoy/gotouch/releases/download/v1.11.0/gotouch_1.11.0_Linux_arm64.tar.gz"
      sha256 "1803d108fe369205013766df6e9bbad98c17dc6872965290dd0c9ca2530ed365"

      def install
        bin.install "gotouch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/denizgursoy/gotouch/releases/download/v1.11.0/gotouch_1.11.0_Linux_x86_64.tar.gz"
      sha256 "e6bc1a9cba2e3187da371035526911eded55f91cd76c1aa65b8271130980eda2"

      def install
        bin.install "gotouch"
      end
    end
  end
end
