# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mugo < Formula
  desc "go template executor"
  homepage "https://github.com/rytsh/mugo"
  version "0.7.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rytsh/mugo/releases/download/v0.7.2/mugo_Darwin_arm64.tar.gz"
      sha256 "67116d850c7fcabb85d8ef0c3b77585a9f3c6ab0b973f949c7fbe5856edd64f5"

      def install
        bin.install "mugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rytsh/mugo/releases/download/v0.7.2/mugo_Darwin_x86_64.tar.gz"
      sha256 "2c7efb4a030f65ddb9c9cdfc9b543648bcb37480daaa42f92cc8d268eb55233d"

      def install
        bin.install "mugo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rytsh/mugo/releases/download/v0.7.2/mugo_Linux_arm.tar.gz"
      sha256 "143018dbed51f085e722554e69908cbf68770a5f4e2af2b97c6cfe4eed87a329"

      def install
        bin.install "mugo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rytsh/mugo/releases/download/v0.7.2/mugo_Linux_arm64.tar.gz"
      sha256 "855a0257947430b71b284a94192ca36b6c82cd80444be1ae3fa356e5e4085dd6"

      def install
        bin.install "mugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rytsh/mugo/releases/download/v0.7.2/mugo_Linux_x86_64.tar.gz"
      sha256 "168cc1e6376c5da60cd93baf86c2b9955e1a210d57b81ac5171fa7dc19dad827"

      def install
        bin.install "mugo"
      end
    end
  end
end
