# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mugo < Formula
  desc "go template executor"
  homepage "https://github.com/rytsh/mugo"
  version "0.7.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rytsh/mugo/releases/download/v0.7.4/mugo_Darwin_arm64.tar.gz"
      sha256 "d3cc7afab5d2fc4906907a8119c5c77f9e804146f365ebcfc20fd54c8bcba7ca"

      def install
        bin.install "mugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rytsh/mugo/releases/download/v0.7.4/mugo_Darwin_x86_64.tar.gz"
      sha256 "3aa0610cac0b801eac6889fb4bac47f1112c7521acdb2a869fe7dc1ff239e399"

      def install
        bin.install "mugo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rytsh/mugo/releases/download/v0.7.4/mugo_Linux_arm.tar.gz"
      sha256 "58204c763d58d64023343c5a00dde59f478e011fac2401cfd6f2e83a574b1025"

      def install
        bin.install "mugo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rytsh/mugo/releases/download/v0.7.4/mugo_Linux_arm64.tar.gz"
      sha256 "7210d7ac722c555b7a17440b2a310154fabe1e01f0baa351cb2d4b7235b3d808"

      def install
        bin.install "mugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rytsh/mugo/releases/download/v0.7.4/mugo_Linux_x86_64.tar.gz"
      sha256 "3487775f3c6b56685051166d05d2a3fe4276c2f5803e7de70d368be971448d34"

      def install
        bin.install "mugo"
      end
    end
  end
end
