# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mugo < Formula
  desc "go template executor"
  homepage "https://github.com/rytsh/mugo"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rytsh/mugo/releases/download/v0.1.0/mugo_Darwin_x86_64.tar.gz"
      sha256 "b7871151fcedc10ddaefb5bec9f4ba1951ee15056b1ea3acd9361d3bdc000cfe"

      def install
        bin.install "mugo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rytsh/mugo/releases/download/v0.1.0/mugo_Darwin_arm64.tar.gz"
      sha256 "c82f00fae610831de7b3d72325bb9fecc73e210c06f6e0992c36810d17e0be17"

      def install
        bin.install "mugo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rytsh/mugo/releases/download/v0.1.0/mugo_Linux_armv6.tar.gz"
      sha256 "85650110ef4bfc338f291709e3631a129b725ac873205d357e9e982406cb52a3"

      def install
        bin.install "mugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rytsh/mugo/releases/download/v0.1.0/mugo_Linux_x86_64.tar.gz"
      sha256 "836f1c71094f8a2d40f8b1e9e6ee3323d56f17fdccbed3601e4d74e46335e8ee"

      def install
        bin.install "mugo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rytsh/mugo/releases/download/v0.1.0/mugo_Linux_arm64.tar.gz"
      sha256 "198a878401876d654e7c55f404f5eff74155f3887d4282d394311400b3812669"

      def install
        bin.install "mugo"
      end
    end
  end
end
