# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turna < Formula
  desc "swiss knife for services"
  homepage "https://github.com/worldline-go/turna"
  version "0.5.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/worldline-go/turna/releases/download/v0.5.4/turna_Darwin_arm64.tar.gz"
      sha256 "a702b0cc1358bfc3b518e30f818d2b4380a7c214c80df51abcf4336a4e5b3007"

      def install
        bin.install "turna"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/worldline-go/turna/releases/download/v0.5.4/turna_Darwin_x86_64.tar.gz"
      sha256 "535d8eeca758cbaefc3c34495b13c7af0ab7ff788b67ec24f47d9d56cb9a563f"

      def install
        bin.install "turna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/worldline-go/turna/releases/download/v0.5.4/turna_Linux_arm.tar.gz"
      sha256 "2f95b1b5239f6916cad7dc6673ff563857d1f79dc260b2cc35a179af5b07ae42"

      def install
        bin.install "turna"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/worldline-go/turna/releases/download/v0.5.4/turna_Linux_arm64.tar.gz"
      sha256 "24ea4005a887116a868aed5f7acceb81a1c6c79684e69615ffbe13567b095288"

      def install
        bin.install "turna"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/worldline-go/turna/releases/download/v0.5.4/turna_Linux_x86_64.tar.gz"
      sha256 "3d6caad2fe721732d3b0610d3844480c3501a8d10e77281c2fd5b259868713ab"

      def install
        bin.install "turna"
      end
    end
  end
end
